# Generated by Django 5.0.2 on 2024-02-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boton", models.CharField(max_length=100)),
                ("usuario", models.CharField(max_length=100)),
                ("fecha", models.DateTimeField()),
            ],
        ),
    ]
