# Generated by Django 5.0.2 on 2024-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "principal",
            "0002_alter_accion_options_alter_registroaccion_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroDatosUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_contacto", models.CharField(max_length=20)),
                ("tipo_documento", models.CharField(max_length=50)),
                ("numero_documento", models.CharField(max_length=10)),
                ("nombres", models.CharField(max_length=20)),
                ("apellidos", models.CharField(max_length=20)),
                ("sede_contacto", models.CharField(max_length=100)),
                ("ip_dispositivo", models.CharField(max_length=100)),
                ("ubicacion_dispositivo", models.CharField(max_length=100)),
            ],
        ),
    ]
