# Generated by Django 5.0.2 on 2024-04-29 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("principal", "0004_remove_registrodatosuser_ubicacion_dispositivo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Encuesta",
        ),
    ]
